### ISSUE TITLE
请问进入网站后，所有的path都加到cache中，是怎么做到的

### ISSUE THREAD

**Issue by Laumlin** [littlematch0123/blog-client#4]
![2018-10-04 16-13-43](https://user-images.githubusercontent.com/31385709/46461328-01709000-c7f1-11e8-99f2-a53709a3bffd.png)

**Comment by littlematch0123** [comment]
离线缓存是先访问页面，离线后才能访问该页面的缓存。
离线缓存是通过sw-precache-webpack-plugin插件实现的。服务器端渲染和浏览器端渲染不太一样。
这个项目是服务器端渲染，主要代码如下
`runtimeCaching: [{
          urlPattern: '/',
          handler: 'networkFirst'
        },
        {
          urlPattern: /\/(posts|categories|users|likes|comments)/,
          handler: 'networkFirst'
        },
      ]
    })
`
详细情况详见[网站PWA升级](https://www.cnblogs.com/xiaohuochai/p/9173959.html)
